Vagrant.configure("2") do |config| 
  config.vm.define :ansible do |main1| 
    main1.vm.box = "kors89/centos7"
    main1.vm.hostname = "ansible" 
    main1.vm.network :forwarded_port, guest: 80, host: 8000 
    main1.vm.network :private_network, ip: "192.168.100.12" 
    main1.vm.provider :virtualbox do |v| 
     v.customize ["modifyvm", :id, "--usb", "on"]
     v.customize ["modifyvm", :id, "--usbehci", "off"]
     v.customize ["modifyvm", :id, "--cpuexecutioncap", "75", "--memory", "1024", "--cpus", "1", "--name", "ansible"]
    end 
   main1.vm.provision "shell", path: "script_ansible.sh"
   main1.vm.provision "file", source: "hosts", destination: "/usr/tmp/hosts"
   main1.vm.provision "file", source: "id_rsa", destination: "/usr/tmp/id_rsa"
   main1.vm.provision "shell", path: "script_ansible_2.sh"
  end 
  
  config.vm.define :web do |main2| 
    main2.vm.box = "kors89/centos7"
    main2.vm.hostname = "web" 
    main2.vm.network :forwarded_port, guest: 80, host: 8001 
    main2.vm.network :private_network, ip: "192.168.100.13" 
    main2.vm.provider :virtualbox do |v| 
     v.customize ["modifyvm", :id, "--usb", "on"]
     v.customize ["modifyvm", :id, "--usbehci", "off"]
     v.customize ["modifyvm", :id, "--cpuexecutioncap", "75", "--memory", "1024", "--cpus", "1", "--name", "web"]
    end 
    main2.vm.provision "shell", path: "script.sh"
    main2.vm.provision "file", source: "hosts", destination: "/usr/tmp/hosts"
    main2.vm.provision "file", source: "id_rsa.pub", destination: "/usr/tmp/id_rsa.pub"
    main2.vm.provision "shell", path: "script_2.sh"
  end 
 
config.vm.define :db do |main3| 
    main3.vm.box = "kors89/centos7"
    main3.vm.hostname = "db" 
    main3.vm.network :forwarded_port, guest: 80, host: 8002 
    main3.vm.network :private_network, ip: "192.168.100.14" 
    main3.vm.provider :virtualbox do |v| 
     v.customize ["modifyvm", :id, "--usb", "on"]
     v.customize ["modifyvm", :id, "--usbehci", "off"]
     v.customize ["modifyvm", :id, "--cpuexecutioncap", "75", "--memory", "1024", "--cpus", "1", "--name", "db"]
    end
    main3.vm.provision "shell", path: "script.sh"
    main3.vm.provision "file", source: "hosts", destination: "/usr/tmp/hosts"
    main3.vm.provision "file", source: "id_rsa.pub", destination: "/usr/tmp/id_rsa.pub"
    main3.vm.provision "shell", path: "script_2.sh"
  end 
end 
