- name: 1. install MariaDB
  yum: name={{ item }} state=latest
  with_items:
    - mariadb
    - mariadb-server
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: 2. start MariaDB
  service: name=mariadb state=started enabled=yes

- name: 3. configure SELinux
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: 4. open 3306 port in firewall
  command: firewall-cmd --zone=public --add-port=3306/tcp --permanent

- name: 5. reload firewall
  command: firewall-cmd --reload

- name: 6. Create Application DB User
  mysql_user: name={{ dbuser }} password={{ dbpassword }} priv=*.*:ALL host='%' state=present
  
- name: 7. configure SELinux
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes